### ISSUE TITLE
Something went wrong during completion. Reason:

### ISSUE THREAD

**Issue by hdmbn** [father-bot/chatgpt_telegram_bot#425]
I get this error whenever the GTP answer is long, especially when generating code for me.

**Comment by hdmbn** [comment]
In the docker logs I can see these errors:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "bot/bot.py", line 307, in message_handle
    await task
  File "bot/bot.py", line 212, in message_handle_fn
    await update.message.reply_text(f"Starting new dialog due to timeout (<b>{config.chat_modes[chat_mode]['name']}</b> mode) ✅", parse_mode=ParseMode.HTML)
  File "/usr/local/lib/python3.8/site-packages/telegram/_message.py", line 1041, in reply_text
    return await self.get_bot().send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 2598, in send_message
    return await super().send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 760, in send_message
    return await self._send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 488, in _send_message
    result = await super()._send_message(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 512, in _send_message
    result = await self._post(
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 419, in _post
    return await self._do_post(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 326, in _do_post
    return await self.rate_limiter.process_request(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_aioratelimiter.py", line 247, in process_request
    return await self._run_request(
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_aioratelimiter.py", line 203, in _run_request
    return await callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 450, in _do_post
    return await request.post(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 288, in _request_wrapper
    raise exc
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 274, in _request_wrapper
    code, payload = await self.do_request(
  File "/usr/local/lib/python3.8/site-packages/telegram/request/_httpxrequest.py", line 216, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason: Response payload is not completed
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f03a4c7dc70>
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
Something went wrong during completion. Reason:
`

**Comment by TerminalTorture** [comment]
> I get this error whenever the GTP answer is long, especially when generating code for me.

Yeah me too I hope this can get resolved
